services:
  app:
    container_name: app-t2c
    image: app-t2c
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: ${TZ}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      SERVER_HOST: ${SERVER_HOST}
      NODE_APP_INSTANCE: ${NODE_APP_INSTANCE}
    command: bash -c "npm i && npm run dev"
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - t2c

  nginx:
    container_name: nginx-t2c
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/logs:cached
    links:
      - app
    depends_on:
      - app
    networks:
       t2c:
         aliases:
           - t2c.docker

networks:
  t2c:
    name: "telegram-network"
    external: false
